### ISSUE TITLE
Is it possible to implement knocking in react native

### ISSUE THREAD

**Issue by gopidevarapalli** [daily-co/react-native-daily-js#10]
![image](https://user-images.githubusercontent.com/34371835/119370025-71015980-bcd2-11eb-904b-7b25943bed16.png)
![image](https://user-images.githubusercontent.com/34371835/119370576-0bfa3380-bcd3-11eb-9e88-969fb0639b1b.png)

In web we are able to see knocking system i.e Requesting to join and accepting the request from owner.  

But from react native mobile app we are able to join directly even though enable_knocking set to true and is_owner set to true/false for owner/participant respectively.
Is it possible in react native to implement the same functionality as mentioned the screenshots?

**Comment by kompfner** [comment]
* Yes, APIs are available to let you build your own “lobby”!
* When joining a private room with knocking enabled, a participant will successfully join (they’ll get a “joined-meeting” event, etc), but `accessState()` will show “lobby”). In this state, they should **NOT** be able to see other participants’ audio or video and vice versa.
* This participant can then call `requestAccess()` to request “full” access
* The owner can listen to the `waiting-participant-added` event to detect that a new participant is awaiting “full” access to the meeting, and grant the requested access with a call to `updateWaitingParticipant()`
* See our reference docs for more info on how to use these methods and events. All relevant programmatic access control methods are listed in [these release notes](https://github.com/daily-co/daily-js/releases/tag/daily-js-2021-03-09-0.10.0).

Closing the issue, as it appears not to be a bug (but of course, let me know if I've misunderstood!) For troubleshooting and help using our APIs, don't hesitate to hit up help@daily.co.

**Comment by gopidevarapalli** [comment]
when I try to call updateWaitingParticipant('5f08d070-c94a-4a8b-86db-5158b5d1aa29', {grantRequestedAccess:true}) it is throwing error like below.

updateWaitingParticipant() only supported for joined meetings.

Do you have any pre built react native code for this functionality so that we can take reference from there.

**Comment by chadbailey59** [comment]
Hi, can you email help@daily.co so we can help you directly? Thanks!
