### ISSUE TITLE
How to implement FullScreen View. requestFullscreen()[FEATURE-REQUEST]

### ISSUE THREAD

**Issue by gopidevarapalli** [daily-co/react-native-daily-js#13]
We would like to implement fullscreen view for screenshare videos/camera videos. In the reference documents it seems requestFullscreen() is not supported to React Native.
![image](https://user-images.githubusercontent.com/34371835/120618610-ddb9e800-c478-11eb-8708-a1a64e13887f.png)

Is there any possible way to do it? And when can we expect requestFullscreen() method support for react native?

**Comment by philmillman** [comment]
The methods for fullscreen are directly related to [browser](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) APIs and only available in Prebuilt as such. If you would like to implement something similar in React Native, it is certainly possible but outside the scope of `react-native-daily-js` as it exists. If we ever implement the React Native equivalent of Prebuilt, we will take this under consideration.
