### ISSUE TITLE
requestFullScreen() for mobile version

### ISSUE THREAD

**Issue by rajasekhar-github** [daily-co/react-native-daily-js#14]
# requestFullScreen() for mobile version

We need to Full screen option on mobile version with call object.

Screen sharing doing web version and the same we are view on mobile control. Due the lower screen the Video control was not clear.

Could you please consider this option mobile version also? So this was very helpful option.

![Capture](https://user-images.githubusercontent.com/68837113/120672541-090bf980-c4b0-11eb-98a1-8dc89ff23faa.JPG)

**Comment by philmillman** [comment]
The methods for fullscreen are directly related to browser APIs and only available in Prebuilt as such. If you would like to implement something similar in React Native, it is certainly possible but outside the scope of react-native-daily-js as it exists today. If we ever implement the React Native equivalent of Prebuilt, we will take this under consideration.
