### ISSUE TITLE
BUG - user_id in participant-updated incorrect

### ISSUE THREAD

**Issue by thorbenprimke** [daily-co/react-native-daily-js#15]
# Expected behavior

The `participant-updated` should always have the `user_id` that was provided to the `/meeting-tokens` rest endpoint. 

# Describe the bug (unexpected behavior)

The first time `participant-updated` is triggered, the `user_id` actually contains the `session_id`. 

```
{
	"action": "participant-updated",
	"participant": {
		"audio": true,
		"cam_info": {},
		"joined_at": 1970 - 01 - 01 T00: 00: 00.000 Z,
		"local": true,
		"owner": false,
		"record": false,
		"screen": false,
		"screen_info": {},
		"session_id": "cdf16063-b52a-458e-db18-51a8399ed056",
		"tracks": {
			"audio": [Object],
			"screenAudio": [Object],
			"screenVideo": [Object],
			"video": [Object]
		},
		"user_id": "cdf16063-b52a-458e-db18-51a8399ed056",
		"user_name": "ThorbenPrimke",
		"video": true,
		"will_eject_at": 1970 - 01 - 01 T00: 00: 00.000 Z
	}
}
```

Subsequent updates are correct: 

```
{
	"action": "participant-updated",
	"participant": {
		"audio": false,
		"cam_info": {},
		"joined_at": 1970 - 01 - 01 T00: 00: 00.000 Z,
		"local": true,
		"owner": false,
		"record": false,
		"screen": false,
		"screen_info": {},
		"session_id": "cdf16063-b52a-458e-db18-51a8399ed056",
		"tracks": {
			"audio": [Object],
			"screenAudio": [Object],
			"screenVideo": [Object],
			"video": [Object]
		},
		"user_id": "35",
		"user_name": "ThorbenPrimke",
		"video": true,
		"videoTrack": {
			"_constraints": [Object],
			"_enabled": true,
			"_managedByDaily": true,
			"_settings": [Object],
			"id": "7B171E37-39EA-45CE-BFF4-9209B7FDC8C9",
			"kind": "video",
			"label": "7B171E37-39EA-45CE-BFF4-9209B7FDC8C9",
			"muted": false,
			"readyState": "live",
			"remote": false
		},
		"will_eject_at": 1970 - 01 - 01 T00: 00: 00.000 Z
	}
}
```

# Steps to reproduce

- Use the SDK to create a room. 
- Use the SDK to get a meeting token and provide a user_id in the properties
- Subscribe to events and see the above out. 

# Screenshots

None

# System information 

```
    "@daily-co/react-native-daily-js": "^0.12.0",
    "@daily-co/react-native-webrtc": "^1.89.2-daily.2",
```

* Device: iOS and Android)
* OS, version: 14.6 and 11
* Browser, version: N/A

# Additional context

None

**Comment by kompfner** [comment]
This one, too (like [this one](https://github.com/daily-co/react-native-daily-js/issues/17)), has a fix being validated, which should hopefully make the next server-side deployment. Stay tuned, and thanks!

**Comment by thorbenprimke** [comment]
@kompfner - thanks for the update on this and other issue. Server-side / backend fixes are the best. 

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia4.giphy.com%2Fmedia%2FmXnO9IiWWarkI%2Fgiphy.gif&token=awesome" data-gitmeme-token="awesome"><img src="https://media4.giphy.com/media/mXnO9IiWWarkI/giphy.gif" title="Created by gitme.me with /awesome"/></a>

**Comment by kompfner** [comment]
The fix was just deployed. Give it a whirl! Thanks again for reporting.
