### ISSUE TITLE
BUG - Android Video Off Initially -> Does Not Turn On / Stays Black After Video Track On

### ISSUE THREAD

**Issue by thorbenprimke** [daily-co/react-native-daily-js#17]
# Expected behavior
A participant joins a room that has video off by default. After they joined, they turn on the video. The video should then  be visible for all other participants. 

# Describe the bug (unexpected behavior)
On Android, the video stays black whenever a particpants turns it on. If the video is turned off and turned on a second time, the video is received by other participants. 

# Steps to reproduce
1) Setup the playground app on both iOS and Android
2) Join a room that has video off by default 
3) Turn on video on both iOS and Android
4) Notice that Android video is received on iOS but iOS video is not received / displayed on Android
5) Toggle the video on iOS and see it show up on Android

# Screenshots

# System information 

```
    "@daily-co/react-native-daily-js": "^0.13.0",
    "@daily-co/react-native-webrtc": "1.89.2-daily.3",
```

* Device: iOS and Android
* OS, version: 14.6 and 11
* Browser, version: N/A

# Additional context

https://user-images.githubusercontent.com/741767/129393014-65faa99b-e784-4072-be8f-8ceba291e676.mov

**Comment by kompfner** [comment]
Just wanted to give an update: we're currently validating a fix which we hope to get into an upcoming server-side deployment—so far it doesn't seem like a react-native-daily-js version bump will be necessary for this one. Stay tuned; we'll post updates here. Thanks so much for reporting!

**Comment by kompfner** [comment]
The fix was just deployed. Give it a whirl! Thanks again for reporting.
