### ISSUE TITLE
BUG: does not build on M1 mac for iOS simulator

### ISSUE THREAD

**Issue by raymondpebble** [daily-co/react-native-daily-js#18]
# Expected behaviour

`npx react-native run-ios` runs a react native app that uses `react-native-daily-js` on the ios simulator

# Describe the bug (unexpected behavior)

`npx react-native run-ios` fails with: 

```
node_modules/@daily-co/react-native-webrtc/ios/RCTWebRTC/WebRTCModule.h:15:9: fatal error: 'WebRTC/RTCMediaStream.h' file not found
#import <WebRTC/RTCMediaStream.h>
```

```
node_modules/@daily-co/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m:10:9: fatal error: 'WebRTC/RTCCameraVideoCapturer.h' file not found
#import <WebRTC/RTCCameraVideoCapturer.h>
```

```
node_modules/@daily-co/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m:15:9: fatal error: 'WebRTC/RTCConfiguration.h' file not found
#import <WebRTC/RTCConfiguration.h>
```

```
node_modules/@daily-co/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+VideoTrackAdapter.m:11:9: fatal error: 'WebRTC/RTCVideoRenderer.h' file not found
#import <WebRTC/RTCVideoRenderer.h>
```

```
node_modules/@daily-co/react-native-webrtc/ios/RCTWebRTC/WebRTCModule.m:16:9: fatal error: 'WebRTC/RTCDefaultVideoDecoderFactory.h' file not found
#import <WebRTC/RTCDefaultVideoDecoderFactory.h>
```

# Steps to reproduce

1. Have a react native app using `react-native-daily-js`
2. `npx react-native run-ios` targeting iOS simulator

# System information 

 

* Device: M1 Macbook Air, 2020
* OS, version: macOS Big Sur 11.3.1
* React native version: 0.63.1
* "@daily-co/react-native-daily-js": "0.13.0"
* "@daily-co/react-native-webrtc": "1.89.2-daily.3"

# Additional context

Maybe this is due to `react-native-webrtc` not supporting M1 yet? If that's the case, would you be able to add support for M1 in the daily fork of `react-native-webrtc`?

**Comment by raymondpebble** [comment]
Bump, just wondering if there's any update on this :) Our team is looking to use daily and this is a barrier for us.

**Comment by ariboren** [comment]
Have you tried running everything in Rosetta? Xcode, terminal/iTerm, simulator. I believe the issue is related to the WebRTC framework only being compiled for x86.

**Comment by filipi87** [comment]
Hi @raymondpebble 

The `react-native-webrtc` project works on M1.

Are you able to reproduce the same bug using our sample project ? 
https://github.com/daily-co/react-native-daily-js-playground

**Comment by raymondpebble** [comment]
It looks like `react-native-webrtc` added support for the ios simulator on M1 in https://github.com/react-native-webrtc/react-native-webrtc/releases/tag/1.94.0, but this hasn't been merged to the daily fork yet. Would you be able to do so and do a new daily release?

**Comment by filipi87** [comment]
Hi @raymondpebble, we are already working on merging the changes from the 1.94 to our branch. I hope I can give you some news in the next few day.

**Comment by feighter09** [comment]
@filipi87 any update here? My team is also blocked because we're not able to run on M1; running via rosetta results in very long compile times.

**Comment by filipi87** [comment]
Hi @feighter09 

It is still in progress the validation using the version 1.94.

An alternative to running Terminal in Rosetta 2 is to set the architecture with arch -x86_64:
```
# install ffi
sudo arch -x86_64 gem install ffi
# install cocoapods dependencies
arch -x86_64 pod install
# run ios
arch -x86_64 npm run ios
```

So far, we are not facing long compile times executing like that.

**Comment by viggyfresh** [comment]
any updates? still getting burned by this 😢

**Comment by filipi87** [comment]
Hi. 

The next release of `react-native-daily-js` will be dependent on `react-native-webrtc 1.94.1 ` and we are expecting to release that mid-to-late next week.

In internal tests, now we are facing no problems to execute on M1. That is the environment we are using:
```
  - pod version: 1.11.2.  ("pod --version")
  - ffi version: 1.15.5.  ("gem info ffi")
  - gem version: 3.0.3.1 ("gem info ethon")
```

The tests have been made with the latest version of playground, which is now using the version 0.66 of the react-native, which has also some fixes for building on iOS on Apple Silicon (M1).

**Comment by filipi87** [comment]
Hi,

At the middle of last month, we released a new version of `react-native-daily-js`, which is based on the latest version `1.94.1` of the upstream `react-native-webrtc` project.

You can see the release notes here: https://github.com/daily-co/react-native-daily-js/releases/tag/react-native-daily-js-2022-02-16-0.21.0

If you face any other issue related to that, please let me know, open a new issue describing how your environment is (pod, ffi and gem versions), and the logs from both simulator and react-native.

Please use the latest version of our playground app: https://github.com/daily-co/react-native-daily-js-playground
