### ISSUE TITLE
User prompted for microphone permissions when joining call while muted

### ISSUE THREAD

**Issue by ariboren** [daily-co/react-native-daily-js#19]
# Expected behavior

With `audioSource: false` in the join properties and `start_audio_off: true` in the token properties, a user should only be prompted to grant microphone permissions when they try to enable their microphone.

# Describe the bug (unexpected behavior)

The user is prompted to grant microphone permissions when joining the call, even though they expect to be muted.

# System information 

Reproducing on:
- iPhone 12 simulator running iOS 14.3
- iPhone 11 Pro Max running iOS 14.7.1
- @daily-co/daily-js@0.18.0
- @daily-co/react-native-daily-js@0.15.0

 

# Additional context

In our application, many users will be connecting in "listen-only" mode, and it will be off-putting and confusing to users to be prompted for mic permissions. It would be ideal to defer that permissions request until the user intentionally enables their mic.

**Comment by filipi87** [comment]
Hi @ariboren ,

The `audioSource` and `videoSource` properties, you should pass false only if the participant's audio and video should remain disabled during the entire call ( https://docs.daily.co/reference/rn-daily-js/daily-iframe-class/properties ). If you intend to make it possible for the user to open his audio or video during the call, you should not change those properties.

About the permissions, what you need to do is create your room at Daily passing the following properties:
`start_audio_off: true`
`start_video_off: true`

This way your user will not be prompted to grant permissions.

However, we have a behavior, at our daily-js project, that even when the user requests to open only the audio or video, both the permissions are prompted for the user. 

If you pass the `start_video_off: true` together with the `start_audio_off: true` when creating the room, it should solve your problem. In case you are sure you user wont use the video or audio during the call, you can pass `audioSource: false` and `videoSource: false` in the join properties, It should also solve your problem.

**Tested on:**
@daily-co/daily-js: 0.21
@daily-co/react-native-daily-js: 0.18
