### ISSUE TITLE
BUG: iOS app fails to launch on iOS 15.4

### ISSUE THREAD

**Issue by arham-aiow** [daily-co/react-native-daily-js#24]
# Expected behavior
The app builds fine, but when I try launching it, it throws the following error and prevents the main view from loading.
`node_modules/@daily-co/daily-js/dist/daily-iframe.js: /Users/abcd/Data/abcd/mobile/node_modules/@daily-co/daily-js/dist/daily-iframe.js: Cannot read properties of undefined (reading 'env')`

# Screenshots
![Simulator Screen Shot - iPhone 11 - 2022-03-31 at 20 05 42](https://user-images.githubusercontent.com/102761271/161130774-663206a1-1383-4435-a2c6-1eec9a219758.png)

# System information 
Building on Xcode 12 on Mac with M1 pro chip

 

* Device: iOS simulator (iPhone 11)
* OS, version: iOS 15.4

**Comment by arham-aiow** [comment]
Hi @filipi87,
Thanks for your response on this. I've finally managed to get it working on my project. Here's what didn't work:

- Migrating the project to the same RN version as the playground app
- Trying to build the `daily-js` lib in the `node_modules` folder to see if there might be any issues in the `dist`
- Downgrading `react-native-daily-js` versions to various versions
- Adding a `.env` file to the root, installing `dotenv`, updating the start script to add a `NODE_ENV` tag

After a tough ordeal of trying to make it all work and making all these changes on a mature project, what finally worked was commenting out the `cwd` entry from` module-resolver` in` babel.config.js`

**Comment by filipi87** [comment]
Hi @arham-aiow,

Great, glad you have made It work, and thanks for the feedback about your journey to make It work. 

Let us know if you need any help!
