### ISSUE TITLE
participants video is showing loading 

### ISSUE THREAD

**Issue by gopidevarapalli** [daily-co/react-native-daily-js#3]
participant video is not showing when I create room as private and also my video is not showing to the participants.

It is working fine when room is created privacy as public. How can I workout when room is private. 

Did any face similar issue? Could you please help?

**Comment by burhanyilmaz** [comment]
`callObject.join({ url: 'your room', token: 'your meeting token' });`
@gopidevarapalli

**Comment by gopidevarapalli** [comment]
Can you please tell me how can I define  callObject. Is there any inbuilt
module?

**Comment by gopidevarapalli** [comment]
callObject.join({ url: 'your room', token: 'your meeting token' });

We are doing the same like above. But no luck. still it is showing loading

**Comment by kwindla** [comment]
Hi. We are working on support for private rooms. That should land next week. Does everything work for you with public rooms?

**Comment by vuppunaveen** [comment]
public rooms working fine

**Comment by kwindla** [comment]
Thanks for letting us know. Most of our largest customers use public rooms, for flexibility, and control access by simply allowing the rooms to be randomly named, and not re-using rooms. (Setting exp time any time a room is created.)

We'll definitely ship support for private rooms as soon as we have tested all of the configuration combinations and corner cases.

**Comment by vuppunaveen** [comment]
Thank you .. Please let us know the private availability ?

**Comment by gopidevarapalli** [comment]
Public room working fine. But sometimes it is showing loading along with participant video. Please find the below attachment

![1605678356290](https://user-images.githubusercontent.com/34371835/99490468-e9880600-298f-11eb-911d-9a559f6cd4ef.JPEG)

**Comment by rajasekhar-github** [comment]
> Hi. We are working on support for private rooms. That should land next week. Does everything work for you with public rooms?

Hi team,  any update on this?

**Comment by gopidevarapalli** [comment]
> Hi. We are working on support for private rooms. That should land next week. Does everything work for you with public rooms?

Hi, Public rooms are working fine. When can we expect private room support for react native?

**Comment by thuutin** [comment]
@gopidevarapalli 

I think private rooms are working already if you:
- passing the meeting token with `callObject.join({ url: 'your room', token: 'your meeting token' });`
- use the below API to change the `signaling_impl` of the room to `ws`. Note "HELLO" is the room name, TOKEN is your API_KEY.

curl --request POST \
  --url https://api.daily.co/v1/rooms/HELLO \
  --header 'authorization: Bearer $TOKEN' \
  --header 'content-type: application/json' \
  --data '{"properties":{"signaling_impl":"ws"}}'

**Comment by rajasekhar-github** [comment]
@thuutin Thanks for you reply. I tried the above configuration {"signaling_impl":"ws"} Still no luck. says participants video says keep loading. I read the above setting some blog.

-

**Comment by gopidevarapalli** [comment]
> @gopidevarapalli
> 
> I think private rooms are working already if you:
> 
> * passing the meeting token with `callObject.join({ url: 'your room', token: 'your meeting token' });`
> * use the below API to change the `signaling_impl` of the room to `ws`. Note "HELLO" is the room name, TOKEN is your API_KEY.
> 
> curl --request POST
> --url https://api.daily.co/v1/rooms/HELLO
> --header 'authorization: Bearer $TOKEN'
> --header 'content-type: application/json'
> --data '{"properties":{"signaling_impl":"ws"}}'

I already have tried this with the following private room

Following are my config:-
Room Name: privatemeet
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyIjoicHJpdmF0ZW1lZXQiLCJkIjoiODViMzdlYjQtM2RhYi00NTVmLWI1MjEtZTdmYmNhMWVjYjk4IiwiaWF0IjoxNjA3NDA4ODA5fQ.XnDBaR8SCvBO6PitIiqK5WqomTrmL4pGlUOAjzbYQ64
Meeting URL: https://gopid.daily.co/privatemeet?t=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyIjoicHJpdmF0ZW1lZXQiLCJkIjoiODViMzdlYjQtM2RhYi00NTVmLWI1MjEtZTdmYmNhMWVjYjk4IiwiaWF0IjoxNjA3NDA4ODA5fQ.XnDBaR8SCvBO6PitIiqK5WqomTrmL4pGlUOAjzbYQ64
"signaling_impl":"ws"

**Comment by thuutin** [comment]
How many participants are you testing? and what platforms (web or react-native) that the participants use to join the meeting?

**Comment by gopidevarapalli** [comment]
We are testing with both react native (mobile) and web platforms. The issue is that they both are not syncing. Participant video is showing as loading

**Comment by thuutin** [comment]
@gopidevarapalli 
i managed to use the https://github.com/daily-co/react-native-daily-js-playground (just add the meeting token) to join private meeting. 
maybe you want to take a look.

**Comment by kwindla** [comment]
Private rooms do fail to properly join all participants to the same meeting session now, with web sockets signaling.

**Please do not use private rooms with web sockets signaling, yet.**

We are finalizing a fix for this.

**Comment by vuppunaveen** [comment]
@kwindla  Please confirm us private room support for mobile app ? i hope above issue is resolved .

**Comment by mattieruth** [comment]
Hello all... We officially hit parity in websocket signaling in our last release and so the issues with private rooms using websocket signaling should now be resolved. Thank you for your patience. I'm closing this issue but feel free to open another if you continue to have any issues. And as always, if you have questions, the best way to get in touch is via chat on daily.co.
