### ISSUE TITLE
[FEATURE-REQUEST] Screen sharing

### ISSUE THREAD

**Issue by hahtml** [daily-co/react-native-daily-js#33]
While publishing our video and audio stream, we want to share mobile screen (on both iOS and Android) as our secondary video stream. we migrate from another live stream provider which supports mobile screen share and includes native sample handler files in its SDK. Thus, we are able to implement an app broadcast extension to support screen sharing. Does daily support mobile screen share now? If not, do you guys have the plan to support it in the near future?

**Comment by filipi87** [comment]
Hi @hahtml,

We currently don't support screen sharing on our react native library. Though I know that this item is in our backlog,

I will share this request with our product team, and ask them if we have a schedule of when we intend to start to support this feature.

I will let you know as soon as I have any updates.

And thanks for starting using Daily. =)

**Comment by hahtml** [comment]
@filipi87 Cool. I understand that screen sharing should be implemented in the native realm and that is what I am expecting from Daily iOS and Android SDK. By using the native SDK, I could config and send video frames to SDK to publish streams. LMK if you have any updates.

**Comment by malveo** [comment]
Hi @filipi87, is there any update on this feature? It is an extraordinarily relevant feature for all product companies that need to integrate Daily.co into their mobile applications. Where is this feature in your roadmap to date?

**Comment by filipi87** [comment]
Hi @malveo,

Thanks for sharing this. We still don't have a specific date, but we intend to start to implement It between the end of Q2 or beginning of Q3.

I will let you know as soon as we start to implement It.

**Comment by filipi87** [comment]
Hi,Just to let you know that the development for screen sharing has been completed. The support for screen sharing will be included in version `0.46.0`, which is expected to be released in 2 to 3 weeks.

**Comment by malveo** [comment]
Hi @filipi87, thank you! We're excited for version `0.46.0` to test the feature and share our feedback.

**Comment by filipi87** [comment]
And the version `0.46.0` is available 🎉.

Our [playground app](https://github.com/daily-co/react-native-daily-js-playground) has been updated to use the screen share, so you can see an example of it working there.

For iOS, before using it, you will just need to create an app group and change the playground app to use your app group. All the details are described [here](https://github.com/daily-co/react-native-daily-js#screen-sharing-on-ios).
