### ISSUE TITLE
BUG duplicate symbol '_OBJC_CLASS_$_Message'

### ISSUE THREAD

**Issue by hahtml** [daily-co/react-native-daily-js#34]
duplicate symbol '_OBJC_CLASS_$_Message' in:
    /**/mobile.build/Objects-normal/arm64/Message.o
    /**/react-native-webrtc/libreact-native-webrtc.a(ScreenCapturer.o)

Our project has many native code snippets and exists a class named after `Message`. There is also a class with the same name in `ScreenCapturer` file of customed react-native-webrtc. Considering the potential common usage of `Message` in some hybrid projects, it is better to add a prefix to Daily's [`Message`](https://github.com/daily-co/react-native-webrtc/blob/8e4046c050d9da8f3947ef177740c448a5025c3c/ios/RCTWebRTC/ScreenCapturer.m#L19) class to prevent name conflict.

**Comment by filipi87** [comment]
Hi, thank you for reporting this. 

We generally avoid implementing changes to `react-native-webrtc` unless they are strictly necessary. 

Since this issue has been inactive for so long and we currently have no immediate plans to address it within `react-native-webrtc`, we will be closing it.
