### ISSUE TITLE
WARN TypeError: A.toFixed is not a function.

### ISSUE THREAD

**Issue by gewfy** [daily-co/react-native-daily-js#35]
Hi 👋 Thanks for a great service and library!

Since `0.30.0` all the way up to `0.33.1` we get a bunch of unhandled promise rejection warnings about `toFixed is not a function`. The source of this issue is very hard to debug as the stack trace is obfuscated. Works as expected in `0.29.0`.

Warnings pops-up very sporadic and at different intervals. It does not seem to correlate with any state changes (e.g. muting or new participants). The meeting is not interrupted, but our Sentry logs gets filled up.

Example of obfuscated stack trace:
```
WARN  Possible Unhandled Promise Rejection (id: 1):
TypeError: I.toFixed is not a function. (In 'I.toFixed(l.NUM_DECIMALS)', 'I.toFixed' is undefined)
value@
value@
value@
@
generatorResume@[native code]
r@
s@
@
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.twentyninek.app.cupcake.dev:26002:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.twentyninek.app.cupcake.dev:26134:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.twentyninek.app.cupcake.dev:26021:14
@
ee@
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.twentyninek.app.cupcake.dev:27098:26
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.twentyninek.app.cupcake.dev:27023:17
callTimers@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.twentyninek.app.cupcake.dev:27183:19
__callFunction@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.twentyninek.app.cupcake.dev:2673:36
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.twentyninek.app.cupcake.dev:2430:31
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.twentyninek.app.cupcake.dev:2628:15
callFunctionReturnFlushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.twentyninek.app.cupcake.dev:2429:21
callFunctionReturnFlushedQueue@[native code]
```

# Steps to reproduce

1. Make sure you use 0.30.0 or higher
2. Join a meeting with two or more devices
3. Wait for a couple of minutes
4. Console warnings should start appearing - on both devices

# System information 

* Device: Simulator and real device
* OS, version: reproduced on both iOS 15.5, 16.1. Have not tested android
* React-native: 0.69.5

Thank you!

**Comment by jabirmhd** [comment]
This error is happening to me also.
`Unhandled promise rejection [TypeError: A.toFixed is not a function. (In 'A.toFixed(l.NUM_DECIMALS)', 'A.toFixed' is undefined)]`

``` 
"@daily-co/react-native-daily-js": "^0.33.0",
"@daily-co/react-native-webrtc": "^1.94.1-daily.7",
"react-native": "0.70.5",
```

**Comment by filipi87** [comment]
Hi @gewfy and @jabirmhd ,

Thanks a lot for reporting this.

Could you share a couple of additional informations:
- Is this issue happening on both Android and iOS ? I know that @gewfy had mention which had not tested on Android yet, but curious to know if some of you are also facing It on Android.
- What is the version of react that you are using ? Our [playground app](https://github.com/daily-co/react-native-daily-js-playground) is currently using the version `"react": "18.1.0"`.
- Are you able to reproduce this issue using our [playground app](https://github.com/daily-co/react-native-daily-js-playground) ? 

In the meantime, I will be trying to reproduce this issue on iOS.

Thanks a lot for your help. =)

**Comment by filipi87** [comment]
Hi @gewfy, 

Since the version `1.94.1-daily.6` of `@daily-co/react-native-webrtc` our code is basically the same with your [temp fix](https://github.com/daily-co/react-native-webrtc/compare/main...29ki:daily-react-native-webrtc:fix-iOS-16-support), just the `categoryOptions` are in different order. Have you tested in a different order and the issue was still happening ?

I saw that you were using `"@daily-co/react-native-webrtc": "1.94.1-daily.4"`, have you tried to reproduce the issue with the latest versions ?

**Comment by filipi87** [comment]
We already have an open PR with the fix. I will let you know as soon as we release It. 

Thank you again for reporting this.

**Comment by gewfy** [comment]
Just got back from vacation. Thanks for looking into this @filipi87 !

I saw that `0.35.0` seems to include a fix for this. We'll test it asap. Thank you!

**Comment by gewfy** [comment]
@filipi87 Verified that it's resolved now. Thanks for the fix!
