### ISSUE TITLE
iOS call dies in background after about ~15 seconds

### ISSUE THREAD

**Issue by moulie415** [daily-co/react-native-daily-js#42]
Android seems fine but iOS lasts for around 15 seconds and the call dies, do I need to add something like react native callkeep to keep the app alive or should the app stay alive by itself on iOS?

**Comment by moulie415** [comment]
Ok never mind, I just tested a release build on iOS and it seems to stay awake forever so I guess this isn't really an issue

**Comment by filipi87** [comment]
Hi @moulie415,

You would just need to add `voip`, inside the `UIBackgroundModes`. You can see more details about this inside our [Readme](https://github.com/daily-co/react-native-daily-js). 

But other than that, all should be good, and the app must keep working in the background.

I will close this issue, feel free to reopen in case the above solution doesn't work and you are able to reproduce it.

**Comment by moulie415** [comment]
@filipi87 yes I did already have that but the dev build died after about 15 secs, running iOS in release mode seems to do the trick for me and that's ultimately what matters so don't really consider this an issue anymore, thanks

**Comment by filipi87** [comment]
I see. I will try to reproduce this with a debug build and see if I can find out anything from Apple reporting this behavior. 
Thanks for letting us know about this @moulie415 .
