### ISSUE TITLE
BUG audio level is not supported yet

### ISSUE THREAD

**Issue by hahtml** [daily-co/react-native-daily-js#45]
The audio level feature should be rolled out since react-native-daily-js 0.47 according to the release note and changelog. But neither events [local-audio-level](https://docs.daily.co/reference/daily-js/events/meeting-events#local-audio-level) nor [remote-participants-audio-level](https://docs.daily.co/reference/daily-js/events/meeting-events#remote-participants-audio-level) are exposed.
Same happen to methods [startRemoteParticipantsAudioObserver()](https://docs.daily.co/reference/daily-js/instance-methods/start-remote-participants-audio-level-observer), [stopRemoteParticipantsAudioObserver()](https://docs.daily.co/reference/daily-js/instance-methods/stop-remote-participants-audio-level-observer), [startLocalAudioObserver()](https://docs.daily.co/reference/daily-js/instance-methods/start-local-audio-level-observer) and [stopLocalAudioObserver()](https://docs.daily.co/reference/daily-js/instance-methods/stop-local-audio-level-observer)

**Comment by filipi87** [comment]
Hi @hahtml,

Thank you for catching this. Unfortunately, it appears that this information was mistakenly included in our `react-native-daily-js` release log.

The documentation you've linked to pertains to `daily-js`, not our react-native version. To adapt these features for use in react-native, we would need to implement them differently, as we can't rely on the same APIs used for the web version.

If this feature is important to you, you can change this issue to a feature request.

Once again, thank you for notifying us of this issue.

**Comment by Shubham-Patel-DJ** [comment]
Hi @filipi87, Yes. Requesting you to please mark this as a feature request. These events help bring some activity at UI level. Which makes the Voice/Video call. Interactable and Interesting.

Regards,

**Comment by filipi87** [comment]
Hi @hahtml , @Shubham-Patel-DJ ,

We have added support for the audio level in our latest release, 0.60.0. 
[More details here](https://github.com/daily-co/react-native-daily-js/releases/tag/react-native-daily-js-2024-04-04-0.60.0).

Let me know in case you need any help.
