### ISSUE TITLE
expo-location/expo-task-manager service interfering with daily.co service

### ISSUE THREAD

**Issue by AbrahamX3** [daily-co/react-native-daily-js#46]
# Expected behavior
My app is able to track location while in the app and in the background, if app is killed, location tracking service is also killed. Using `expo-location@^16.1.0` and `expo-task-manager@^11.3.0`, I am able to track the user's location, the following code Is what I use to set up a task and track location in the foreground and background.

 ```ts
    const LOCATION_TASK_NAME = "get-location";

    TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }) => {
      if (error) {
        console.error("ERROR: ", error);
        return;
      }
    
      if (data) {
        const { locations } = data as DeviceLocations;
        const location = locations[0];
    
        if (location) {
          // save location code
        }
      }
    });

      await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
        accuracy: Location.Accuracy.Highest,
        distanceInterval: 0.5,
        showsBackgroundLocationIndicator: true,
        pausesUpdatesAutomatically: true,
        mayShowUserSettingsDialog: true,
        foregroundService: {
          notificationColor: "#1d4ed8",
          notificationTitle: "Tracking Location",
          notificationBody: "This app is tracking your location",
          killServiceOnDestroy: true,
        },
        timeInterval: 1000 * 5,
      });
```
This code was written following the [Expo example](https://docs.expo.dev/versions/latest/sdk/task-manager/#configuration-for-standalone-apps)

When starting the location service, it pushes a sticky notification with the info provided from `foregroundService`, when app is killed, task gets killed and notification goes away.

# Describe the bug (unexpected behavior)

When killing the application and notification go away, after a while it somehow pops up again, while the app is completely closed, you can't dismiss the notification since it's sticky, so you either have to force close the application or go in the application and close it again. But even then it still manages to push a notification after a while. 

At first, I thought, “oh it's just the notification”, since during development there appears to be no background logs of the location service, but during production, if we take a look at battery usage, it clearly is doing something in the background.

My only workaround has been using the following method manually when the user decides to log out, I use the method, which is not ideal for my users. Only then do the pop's stop appearing, since there's no other way to kill the task when the app is closed.

```ts
await TaskManager.unregisterAllTasksAsync();
```
This all started when using daily.co, completely removing all daily packages, the issue does not occur.

I am using the following package versions
```
@config-plugins/react-native-webrtc@"^7.0.0",
@daily-co/config-plugin-rn-daily-js@"^0.0.3",
@daily-co/react-native-daily-js@"^0.51.0",
@daily-co/react-native-webrtc@^111.0.0-daily.2",

Other Dependencies used by Daily
@react-native-async-storage/async-storage@^1.15.7 or latest @react-native-async-storage/async-storage@^1.19.3
react-native-background-timer@^2.3.1
```
By only installing @daily-co/react-native-daily-js and using expo prebuild without necessarily using any library in the app, it triggers the notification (the issue).

# Steps to reproduce

1. Install daily on expo using the official documentation for Expo 49, you could set up a simple daily screen, but it's not necessary since the issue still appears even when not using any code, or you can just install @daily-co/react-native-daily-js (issue simply comes up by installing library)
2. Install expo-location and expo-task-manager following Expo's official documentation [Expo example](https://docs.expo.dev/versions/latest/sdk/task-manager/#configuration-for-standalone-apps)
3. Build for development (standalone, not using expo go)
5. Open the application, wait for location service to start and for the notification push.
5. Close the application, make sure the foreground notification closes as well.
6. Wait a while for notification to pop up. In development, it might trigger a reload for some reason.

# Screenshots
Might not be related, but, I do get this following error, looking around other issues on github I've ignored it via ```LogBox.ignoreLogs(["new NativeEventEmitter"]);```

![image](https://github.com/daily-co/react-native-daily-js/assets/78459953/4eb87141-4985-4816-91a4-0f4e591389e6)

# System information 
* Device: Android
* OS, version: Android 10
* Browser, version: N/A

# Additional context

I've tried debugging by removing daily packages one by one and rebuilding, the issue seems to be with @daily-co/react-native-daily-js completely removing it makes the issue go away.

During another debugging session I had, I set up a simple cleanup useEffect that kills the task and stops location tracking like the following:

```ts
 useEffect(() => {
    return () => {
      if (TaskManager.isTaskDefined(LOCATION_TASK_NAME)) {
        console.log("Stopping Task and Location");
        Location.stopLocationUpdatesAsync(LOCATION_TASK_NAME).catch(console.error);
        TaskManager.unregisterAllTasksAsync().catch(console.error);
      }
    };
  }, [TaskManager.isTaskDefined(LOCATION_TASK_NAME)]);
```

Without any daily libraries installed, when I close the app I get the console.log as expected since it is unmounted, but when installing @daily-co/react-native-daily-js and rebuilding, opening app and closing, for some reason I do not get the console.log message anymore for some reason which might be because it doesn't get unmounted when closed?, unsure if it's only an expo-location/expo-task-manager issue anymore after this.

**Comment by filipi87** [comment]
Hi @AbrahamX3, Sorry for the late reply. 

For Android, we have a Foreground service that starts when you join a call and is destroyed either when you leave the call or when the host app is closed. 

Are you still experiencing this issue with the latest version of our SDK and the demo app? We also have an [Expo demo available here](https://github.com/daily-demos/daily-expo-demo) that may be helpful for testing with the latest version.

Regarding the warning you mentioned earlier, it is unrelated to this issue. You can find more details [here](https://github.com/daily-co/react-native-daily-js/issues/21).

**Comment by AbrahamX3** [comment]
Hey @filipi87, thanks for the reply. After upgrading to Expo 50, following the daily upgrade instructions and doing some testing, It does seem to be working "fine" now.

Before when using location services and closing the app, it would remove the background notification. But when using background location services and doing a daily live stream and closing the app, the notification would pop up when I trigger location services in another app and won't get removed. Doing some testing by removing daily from my project made this issue go away.

Now when using location services and closing app it removes the notification like before but when using daily, it now also removes the notification successfully, when triggering location services with another app, it brings up the notification but gets dismissed after a few seconds which is better.

Unsure why that happens, it's a lot better than before though!

Maybe it only lets the daily instance get killed and blocks any other cleanup from happening as soon as app is killed, before it seemed to have been blocking any cleanup from happening; considering it wouldn't run useEffect cleanup functions when I had daily installed in my project.

Thanks for the Expo 50 update!

**Comment by filipi87** [comment]
Hi @AbrahamX3,

> when triggering location services with another app, it brings up the notification but gets dismissed after a few seconds which is better.

Just to be sure here, the notification in this case is the one from the location service, right ? 

> Maybe it only lets the daily instance get killed and blocks any other cleanup from happening as soon as app is killed, before it seemed to have been blocking any cleanup from happening; considering it wouldn't run useEffect cleanup functions when I had daily installed in my project.

I will try to investigate that, to see if there is something we can improve here.

Thank you for your reply!

**Comment by AbrahamX3** [comment]
Hey @filipi87

Thats correct, the notification is from location services. 

Thanks!!

**Comment by filipi87** [comment]
Hi @AbrahamX3,

We have just released a new version, `0.62.0`, where we fixed issue on React Native Android that could prevent the app from doing a proper cleanup when it was destroyed.

Let me know if that has solved your issue. 👍

**Comment by AbrahamX3** [comment]
Hey @filipi87 just tried out version `@daily-co/react-native-daily-js@0.62.0` with `expo@50.0.18` and can confirm it works perfectly now!

From my testing it does seem to respect cleanup functions now, at first I was getting some weird behavior when closing my application and location services were still there but after adding the proper cleanup functions (that should have worked before but didn't work due to daily.co possibly blocking it), it worked perfectly. For example:

```ts
  useEffect(() => {
    if(permission){
       startLocationUpdates();
     }

    // This cleanup function would not get triggered before when 
    // closing my application with daily installed!
    return () => {
      TaskManager.unregisterAllTasksAsync();
    };
  }, [permission]);
```

Now using expo location services and starting a livestream with daily and closing my app, it instantly terminates services and no longer keeps location services running. I also re-did the test that I mentioned above:

> Now when using location services and closing app it removes the notification like before but when using daily, it now also removes the notification successfully, when triggering location services with another app, it brings up the notification but gets dismissed after a few seconds which is better.

Did the test just to confirm it works, and it did!, I use my application, use location services and daily, close it, open another app (for example Twitter, which uses location services, I know this because I get the GPS icon in the nav bar), and it doesn't trigger the location services any more like before because they were successfully cleaned up!

I appreciate you fixing this, thank you!!!

You can probably bump the `@daily-co/react-native-daily-js` version from `0.59.0` to `0.62` on [https://www.npmjs.com/package/@daily-co/config-plugin-rn-daily-js](https://www.npmjs.com/package/@daily-co/config-plugin-rn-daily-js) now :smile:

**Comment by filipi87** [comment]
That is great. Thank you for all your help @AbrahamX3. 👍
