### ISSUE TITLE
BUG can't join call on Android with v0.61.0

### ISSUE THREAD

**Issue by leethree** [daily-co/react-native-daily-js#54]
# Expected behavior

Should join call successfully.

# Describe the bug (unexpected behavior)

Error message:
```
 ERROR  Failed to load call object bundle https://c.daily.co/call-machine/versioned/0.63.0/static/call-machine-object-bundle.js: SyntaxError: No identifiers allowed directly after numeric literal
```

# Steps to reproduce

Join any call on v0.61.0 on Android

# System information 

 

* Device:
* OS, version:
* Browser, version:

# Additional context

It worked fine on v0.60.0

**Comment by filipi87** [comment]
Hi @leethree, thank you for reporting this.

Are you able to reproduce the issue using our [demo app](https://github.com/daily-co/react-native-daily-js-playground) ?

I also need a couple of informations in order to try to reproduce the issue:
- React Native version;
- The versions of all the dependencies that you are using related to Daily;
- OS, version. 
- Are you able to reproduce it on both Android and iOS ?

**Comment by leethree** [comment]
I haven't tested the demo app.

> React Native version;

0.73.7

> The versions of all the dependencies that you are using related to Daily;

@daily-co/react-native-webrtc: 118.0.3-daily.1
We also uses expo 50.0.17

> OS, version.

Android 14

> Are you able to reproduce it on both Android and iOS ?

iOS worked fine. This only happens on Android.

**Comment by filipi87** [comment]
Hi, thank you for the reply.

I have just updated our Expo demo, [PR is still open](https://github.com/daily-demos/daily-expo-demo/pull/8), to match the same versions that you have mentioned, but I am still not able to reproduce it.

These are the current dependencies that we are using there:
```
"dependencies": {
    "@config-plugins/react-native-webrtc": "^8.0.0",
    "@daily-co/config-plugin-rn-daily-js": "0.0.5",
    "@daily-co/react-native-daily-js": "^0.61.0",
    "@daily-co/react-native-webrtc": "^118.0.3-daily.2",
    "@react-native-async-storage/async-storage": "^1.21.0",
    "expo": "~50.0.17",
    "expo-build-properties": "~0.11.1",
    "expo-dev-client": "~3.3.11",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-background-timer": "^2.4.1",
    "react-native-get-random-values": "^1.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
```

It would be nice if you could double check, be sure you are using all the right dependencies. 

If the issue still persists, we would need a minimal reproducible example. My suggestion is that you try to create one base on our [Expo demo](https://github.com/daily-demos/daily-expo-demo), so we can investigate exactly what is happening.

**Comment by filipi87** [comment]
Hi, due to inactivity and an inability to replicate the issue, we're closing it. Feel free to open a new with a minimal reproducible example If the issue still persists.

**Comment by leethree** [comment]
Hi I figured out the cause. We are not using Hermes on Android so it's causing the syntax issue. I managed to reproduce in playground by setting `hermesEnabled=false` in `android/gradle.properties`

![image](https://github.com/daily-co/react-native-daily-js/assets/648142/775d0cf3-61bb-4df4-8bfb-bafd04806f93)
