### ISSUE TITLE
Audio and Video Tracks Not Working After Permission Grant(Android)

### ISSUE THREAD

**Issue by ArturV93** [daily-co/react-native-daily-js#58]
# Expected behavior

After granting microphone and camera permissions on Android when joining a call for the first time, the audio and video tracks are not found(screen 1), allowing the user to participate in the call without having to close and reopen the app.

# Describe the bug (unexpected behavior)

When a user joins a call for the first time on Android, the app requests microphone and camera permissions. Upon accepting, the audio and video tracks are not updated, requiring the user to close and reopen the app to participate in the call. In previous versions, this issue caused the app to crash, but reopening after the crash resolved the issue.

# Steps to reproduce

1. Install the app on an Android device.
2. Join a call for the first time (permissions for microphone and camera are not yet granted).
3. Accept the microphone and camera permissions when prompted.
4. Notice that the audio and video tracks do not update.
5. Close the app and reopen it.
6. Join the call again, and the tracks are then updated properly.

OR

1. The app is already installed on an Android device, and permissions are granted.
2. Go to the app's settings: Settings > Apps > DailyPlayground > Permissions.
3. Change **Camera** and **Microphone** permissions to **'Ask Every Time'.**
4. Open the app and join a call.
5. Accept the microphone and camera permissions when prompted.
6. Notice that the audio and video tracks do not update.
7. Close the app and reopen it.
8. Join the call again, and the tracks are updated properly.

# Screenshots

![Screenshot_20241016_145319_DailyPlayground](https://github.com/user-attachments/assets/ec3bc8b1-f642-4ab2-b30f-70a864609297)

# System information 

https://github.com/daily-co/react-native-daily-js-playground

* Device: Samsung S22
* OS, version: Android 14

# Additional context

In previous versions, this issue caused a crash, but after reopening, the call could proceed without issue once permissions were granted.

**Comment by filipi87** [comment]
Hi @ArturV93, Thank you for reporting this.

I’ve tried to replicate the issue by following both approaches you mentioned, but without success.

I was testing on a Samsung S21, Android 14, using the latest version of our [demo app](https://github.com/daily-co/react-native-daily-js-playground).

A couple of questions:
- Does this issue happen only with the Samsung S22, or can you replicate it on other devices or emulators?
- Are you testing with the latest version of our demo app?
- Could you provide the complete logcat logs, starting from when you open the app until the issue occurs?

**Comment by filipi87** [comment]
Hi @ArturV93, just to give you an update: we’ve been able to replicate the issue. To reproduce it, we need to wait a couple of seconds between when the permission prompt appears in the interface and when we actually accept it. If we accept the permission as soon as it shows, I’m unable to replicate the issue.

We plan to fix this before our next release and I’ll let you know once it’s ready.

**Comment by ArturV93** [comment]
Hi @filipi87, Thanks for the update. I appreciate you working on a fix for the next release. In the meantime, I’ll revert to React Native 0.73.10. As mentioned, with React Native 0.73, the app crashes and requires the user to reopen it after the issue occurs. 
I'm looking forward to your next update!

**Comment by filipi87** [comment]
Hi @ArturV93, another approach you could take (so you don’t need to revert) is to handle permissions directly within your app:
https://reactnative.dev/docs/permissionsandroid

This way, you can ensure the user has provided all required permissions before joining the meeting.

**Comment by filipi87** [comment]
This issue has been fixed in `react-native-daily-js` version [0.70.0](https://github.com/daily-co/react-native-daily-js/releases/tag/react-native-daily-js-2024-10-31-0.70.0).
