### ISSUE TITLE
Bitcode error when archiving iOS project for release

### ISSUE THREAD

**Issue by LordParsley** [daily-co/react-native-daily-js#6]
**Description**

Creating a release build on iOS gives a `WebRTC.framework` error because bitcode is not enabled for the framework.

**Error Message**

```
'.../react-native-daily-js-playground/DailyPlayground/node_modules/@daily-co/react-native-webrtc/ios/WebRTC.framework/WebRTC' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '.../react-native-daily-js-playground/DailyPlayground/node_modules/@daily-co/react-native-webrtc/ios/WebRTC.framework/WebRTC' for architecture arm64
```

**Steps to Reproduce**

- Clone the playground project `react-native-daily-js-playground`.
- Run the iOS setup (including `pod install`).
- Open the `.xcworkspace` file in `ios`.
- Configure the project with your development team set.
- Select a device target or "Any Device" from the targets menu.
- Do a Product -> Archive.

The expected result is a successful build & the archive being available for upload to the App Store (for use on TestFlight, etc.).
Instead, the build fails with the error above.

**Known Issue**

This is a known issue on the main repository: https://github.com/react-native-webrtc/react-native-webrtc/issues/205 & https://github.com/jitsi/jitsi-meet/issues/4209.

* The official advice is to rebuild it with bitcode enabled using this python script: https://webrtc.googlesource.com/src/+/refs/heads/master/docs/native-code/ios/index.md#using-webrtc-in-your-app

* Or to download a prebuilt version using this script: https://github.com/daily-co/react-native-webrtc/blob/main/tools/downloadBitcode.sh

**Suggestion**

Can `react-native-daily-js` maybe add their preferred solution to the iOS getting started docs? I'm presuming that the download option is fine & `WebRTC` is on version `M75`?

**Comment by carloslfu** [comment]
@LordParsley. I have had this error and I execute `./node_modules/@daily-co/react-native-webrtc/tools/downloadBitcode.sh` to fix it.

**Comment by LordParsley** [comment]
Thanks very much @carloslfu ! This worked nicely for me.

I added this convenience script to my `package.json` & execute it as a step in CI:

```
"bitcode": "./node_modules/@daily-co/react-native-webrtc/tools/downloadBitcode.sh",
```

**Comment by mgerh10** [comment]
@LordParsley Do you have a sample CI pipeline for reference? I want to do something similar with my project and would like to ensure I'm running/downloading the bitcode to the proper location.
