### ISSUE TITLE
BUG: Failed to join call: [TypeError: this.nativeUtils().setKeepDeviceAwake is not a function (it is undefined)]

### ISSUE THREAD

**Issue by tanish35** [daily-co/react-native-daily-js#60]
I am running on a Medium_Phone_API_35 from android studio and am trying to join a videocall using the daily.createCallObject.

Failed to join call: [TypeError: this.nativeUtils().setKeepDeviceAwake is not a function (it is undefined)]

This error is being shown upon trying to join a videocall as the package is trying to access a function called setKeepDeviceAwake. What could be the issue ?

**Comment by filipi87** [comment]
This is a native function provided by react-native-daily-js for Android, and it should always be available if our SDK is properly installed.

Could you please provide the following details to help us troubleshoot the issue more effectively ?

- Which version of our SDK are you using?
- Are you using Expo or another framework?
- Can you replicate the issue using one of our demo projects?
  - [React Native Daily JS Playground](https://github.com/daily-co/react-native-daily-js-playground)
  - [Daily Expo Demo](https://github.com/daily-demos/daily-expo-demo/)

**Comment by smadabat1** [comment]
Hey, @tanish35
Greetings. 

Could you let me know if this has been fixed for you? 

Im using Expo and I'm facing this issue on IOS dev build. 

Any help on this would be highly appreciated.
