### ISSUE TITLE
BUG - two mobile users cannot join room

### ISSUE THREAD

**Issue by lander854** [daily-co/react-native-daily-js#8]
When 1 user is  on mobile and 1 on web it works as intended,
but when both users are on mobile the room stays at loading...

# Screenshots
![image](https://user-images.githubusercontent.com/20193717/116835450-f5136600-ab98-11eb-8910-a6e8f698d675.png)

    "@daily-co/react-native-daily-js": "^0.9.0",
    "react-native": "0.63.4",

**Comment by kompfner** [comment]
Thanks for opening the issue. Trying to reproduce this error, but haven't been able to...would you mind sharing how you configured your [Daily room](https://docs.daily.co/reference#list-rooms)?

One difference in our test setup is that I tried it with RN 0.63.3, but my hunch is that that's not it...

**Comment by lander854** [comment]
`const { data: roomData } = await axios.post(
      'https://api.daily.co/v1/rooms',
      {
        properties: {
          exp: meetingEndTime.seconds,
          eject_at_room_exp: true,
          max_participants: 2,
          autojoin: true,
          enable_screenshare: true,
          enable_knocking: false,
          signaling_impl: 'ws',
        },
        privacy: 'public',
      },
      {
        headers: {
          authorization: `Bearer ${dailyco.api_key}`,
        },
      },
    )`

**Comment by lander854** [comment]
Got another lead, it works when the react native debugger is enabled, and it doesn't work when RN is on prod mode..

![image](https://user-images.githubusercontent.com/20193717/117066087-aaabf980-acfe-11eb-9722-855bd14e10c5.png)

**Comment by kwindla** [comment]
That sounds like it might be conflict between two included libraries in the project. Does that ring any bells in terms of React Native bugs you've seen, @kompfner?

**Comment by lander854** [comment]
Just to be clear on the debug mode thing,
when both emulators are on debug mode it works
when one of them is on prod mode, it doest work

**Comment by chadbailey59** [comment]
I'd be happy to get on a call with you and walk through how this is happening. Would you mind sending an email to help@daily.co and reference this issue? Thanks!

**Comment by kompfner** [comment]
A few questions:
* Is there any chance your prod builds are using Hermes? We're aware of an issue where Hermes isn't supported. 
* Are there any console logs or device logs you could share with us? 
* Also, I'm curious what happens when you run on actual devices? (The above screenshots look like emulators, and our testing tends to skew towards devices).
Thanks much!

**Comment by lander854** [comment]
Yep, we're using hermes, gonna test it without it

**Comment by wmatthau** [comment]
looks like hermes was the issue, thanks again

**Comment by sunweiyang** [comment]
@kompfner Will Hermes be supported in the future?

**Comment by kompfner** [comment]
> @kompfner Will Hermes be supported in the future?

Yes. Hermes support is in our internal staging environment as we speak and is planned to go to production this week. It's a server-side change so you should not have to do anything once it lands.

**Comment by kompfner** [comment]
Hermes support is in production now. Let us know if you're still seeing the issue when enabling Hermes.
