### ISSUE TITLE
react-native-webrtc downloadBitcode script fails

### ISSUE THREAD

**Issue by Reggionick** [daily-co/react-native-daily-js#9]
# Expected behavior

Executing the script `./node_modules/@daily-co/react-native-webrtc/tools/downloadBitcode.sh` the react-native-webrtc's iOS framework should be downloaded

# Describe the bug (unexpected behavior)

Running the script the error

```
tar: Error opening archive: Unrecognized archive format
```

is thrown.

# Additional context

This issue is not related to this module itself, but with the forked `daily-co/react-native-webrtc`: the files on binary.com seems no more available

**Comment by LordParsley** [comment]
This appears to be related to Bintray being sunset: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

As of 1 May 2021, Bintray will no longer host files & the script is trying to download the framework & dSYM from https://dl.bintray.com/webrtc-builds/webrtc-builds/M75-1/WebRTC.dSYM.tar.xz.

The main library has updated the script & the files are now hosted on Github: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/tools/downloadBitcode.sh

@kompfner or any other Daily.co maintainers, may we ask you to please merge in the latest tools from upstream? 😊 🙏

**Comment by LordParsley** [comment]
> The main library has updated the script & the files are now hosted on Github: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/tools/downloadBitcode.sh

Though I see the first Github hosted version is https://github.com/react-native-webrtc/react-native-webrtc/releases/download/1.89.0/WebRTC.tar.xz, from when they made the change to download process: https://github.com/react-native-webrtc/react-native-webrtc/commit/f2b66a47f1954e78f9fa940efeb2ffccd81359fb#diff-f9d35d43770d39092a663e665e82ae1d84a9e0da3d0d10c407acada6a40cd281

And that's WebRTC M89 😐

**Comment by kompfner** [comment]
Thanks so much for reporting! Fully agree that it's important to be able to build with bitcode. While you can set "Enable Bitcode" to NO in your app target as a workaround for now, that's not a great long-term solution. We'll work on this. Thanks for bearing with us.

**Comment by LordParsley** [comment]
Thanks very much for taking a look at this @kompfner 👍

**Comment by kompfner** [comment]
This should be resolved with [release 0.11.0](https://github.com/daily-co/react-native-daily-js/releases/tag/react-native-daily-js-2021-05-27-0.11.0). Thanks again for the feedback!
